/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/auth/login": {
    post: operations["login"];
  };
  "/users": {
    /** Optional extended description in CommonMark or HTML. */
    get: operations["getUsers"];
  };
}

export interface components {
  schemas: {
    Image: {
      id?: number;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
      imagesUrls?: string[];
      originalUrl?: string;
      tags?: components["schemas"]["Tag"][];
      uploadedBy?: components["schemas"]["User"];
      uploaderId?: number;
      author?: components["schemas"]["Author"];
      authorId?: number;
      likedBy?: components["schemas"]["User"][];
    };
    Tag: {
      id?: number;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
      title?: string;
      images?: components["schemas"]["Image"][];
    };
    User: {
      id?: number;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
      email?: string;
      username?: string;
      password?: string;
      verificationToken?: string;
      authToken?: string;
      images?: components["schemas"]["Image"][];
      author?: components["schemas"]["Author"];
      authorId?: number;
      likes?: components["schemas"]["Image"][];
    };
    Author: {
      id?: number;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
      name?: string;
      urls?: components["schemas"]["WebsiteUrl"][];
      images?: components["schemas"]["Image"][];
      user?: components["schemas"]["User"];
    };
    WebsiteUrl: {
      id?: number;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
      title?: string;
      url?: string;
      author?: components["schemas"]["Author"];
      authorId?: number;
    };
  };
}

export interface operations {
  login: {
    responses: {
      /** User data */
      200: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": {
          username?: string;
          password?: string;
        };
      };
    };
  };
  /** Optional extended description in CommonMark or HTML. */
  getUsers: {
    responses: {
      /** A JSON array of user names */
      200: {
        content: {
          "application/json": string[];
        };
      };
    };
  };
}

export interface external {}
