/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/auth/login": {
    post: operations["login"];
  };
  "/auth/register": {
    post: operations["register"];
  };
  "/auth/logout": {
    post: operations["logout"];
  };
  "/auth/resend-verification": {
    post: operations["resendVerification"];
  };
  "/auth/verify/{verificationToken}": {
    get: operations["verifyUser"];
  };
  "/authors": {
    get: operations["searchAuthors"];
  };
  "/authors/{authorId}": {
    get: operations["getAuthorById"];
  };
  "/authors/{authorId}/images": {
    get: operations["getAuthorWorks"];
  };
  "/images": {
    get: operations["searchImages"];
    post: operations["createImage"];
  };
  "/images/{imageId}": {
    get: operations["getImageById"];
  };
  "/users/{userId}": {
    get: operations["getUserById"];
  };
  "/users/{userId}/likes": {
    get: operations["getUserLikes"];
  };
  "/users/{userId}/uploads": {
    get: operations["getUserUploads"];
  };
}

export interface components {
  schemas: {
    Image: {
      id: number;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      imagesUrls: string[];
      originalUrl?: string;
      tags: components["schemas"]["Tag"][];
      uploadedBy: components["schemas"]["User"];
      uploaderId: number;
      author: components["schemas"]["Author"];
      authorId: number;
      likedBy: components["schemas"]["User"][];
    };
    Tag: {
      id: number;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      title: string;
      images: components["schemas"]["Image"][];
    };
    User: {
      id: number;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      email: string;
      username: string;
      password: string;
      verificationToken?: string;
      authToken?: string;
      images: components["schemas"]["Image"][];
      author?: components["schemas"]["Author"];
      authorId?: number;
      likes: components["schemas"]["Image"][];
    };
    Author: {
      id: number;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      name: string;
      urls: components["schemas"]["WebsiteUrl"][];
      images: components["schemas"]["Image"][];
      user?: components["schemas"]["User"];
    };
    WebsiteUrl: {
      id: number;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      title: string;
      url: string;
      author: components["schemas"]["Author"];
      authorId: number;
    };
  };
}

export interface operations {
  login: {
    responses: {
      /** User data */
      200: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": {
          username: string;
          password: string;
        };
      };
    };
  };
  register: {
    responses: {
      /** User data */
      200: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": {
          email: string;
          username: string;
          password: string;
        };
      };
    };
  };
  logout: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": string;
        };
      };
    };
  };
  resendVerification: {
    responses: {
      /** Updated user */
      200: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": {
          email: string;
        };
      };
    };
  };
  verifyUser: {
    parameters: {
      path: {
        /** Verification token */
        verificationToken: string;
      };
    };
    responses: {
      /** Updated user */
      200: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
    };
  };
  searchAuthors: {
    parameters: {
      query: {
        q: string;
        page: number;
      };
    };
    responses: {
      /** Authors */
      200: {
        content: {
          "application/json": {
            items: components["schemas"]["Author"][];
            count: number;
            page: number;
            perPage: number;
            pagesCount: number;
          };
        };
      };
    };
  };
  getAuthorById: {
    parameters: {
      path: {
        authorId: number;
      };
    };
    responses: {
      /** Author */
      200: {
        content: {
          "application/json": components["schemas"]["Author"];
        };
      };
    };
  };
  getAuthorWorks: {
    parameters: {
      path: {
        authorId: number;
      };
    };
    responses: {
      /** Author works */
      200: {
        content: {
          "application/json": {
            items: components["schemas"]["Image"][];
            count: number;
            page: number;
            perPage: number;
            pagesCount: number;
          };
        };
      };
    };
  };
  searchImages: {
    parameters: {
      query: {
        q: string;
        page: number;
      };
    };
    responses: {
      /** Images */
      200: {
        content: {
          "application/json": {
            items: components["schemas"]["Image"][];
            count: number;
            page: number;
            perPage: number;
            pagesCount: number;
          };
        };
      };
    };
  };
  createImage: {
    responses: {
      /** New image */
      200: {
        content: {
          "application/json": components["schemas"]["Image"];
        };
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": {
          /** Format: binary */
          image: string;
          author: string;
          tags: string[];
          originalUrl?: string;
        };
      };
    };
  };
  getImageById: {
    parameters: {
      path: {
        imageId: number;
      };
    };
    responses: {
      /** Image */
      200: {
        content: {
          "application/json": components["schemas"]["Image"];
        };
      };
    };
  };
  getUserById: {
    parameters: {
      path: {
        userId: number;
      };
    };
    responses: {
      /** User */
      200: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
    };
  };
  getUserLikes: {
    parameters: {
      path: {
        userId: number;
      };
    };
    responses: {
      /** User likes */
      200: {
        content: {
          "application/json": components["schemas"]["Image"][];
        };
      };
    };
  };
  getUserUploads: {
    parameters: {
      path: {
        userId: number;
      };
    };
    responses: {
      /** User uploads */
      200: {
        content: {
          "application/json": components["schemas"]["Image"][];
        };
      };
    };
  };
}

export interface external {}
